name = "HumanReadableSExpressions"
uuid = "dfa09964-7899-4f24-b5ee-10dc563fda7c"
authors = ["Luke Bemish <lukebemish@lukebemish.dev>"]
version = "0.1.2"

[deps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
StructTypes = "1.10"
julia = "1.8"
